### ISSUE TITLE
Can't play chess on landscape mode 

### ISSUE THREAD

**Issue by isreal6ix** [alaskalinuxuser/app_JustChess#5]
***Expected Behavior***

It is expected that users should be able to play the game on landscape mode 

***Actual Behavior***

The white chess are truncated and not shown to users 

***Test Info***
Device : Infinix hot s
Ram size : 2gb of Ram 

***Procedures to produce bug***

* Open the app 
* Select new game 
* Rotate screen 
* The white chess will be truncated 

***video of bug***

https://youtu.be/OGno2Fjzl1E

**Comment by alaskalinuxuser** [comment]
While not the best fix, a quick fix has been made in Version 1.9 with this commit: https://github.com/alaskalinuxuser/app_JustChess/commit/b0dad96ea34e4eb0efa7d6eb7789a008d034edd7

I added a scroll view, so when in landscape mode, you can center the board on the screen by swiping up or down.

I really appreciate you taking the time to file this report! Thanks, it helps me make a better app!

**Comment by isreal6ix** [comment]
You welcome
