### ISSUE TITLE
Game restarts when minimised 

### ISSUE THREAD

**Issue by isreal6ix** [alaskalinuxuser/app_JustChess#6]
***Actual Behavior***

The game restarts when minimised 

***Ways to produce app***
* open the app 
* play a new game 
* minimise and resume game 
* it'll go to the main menu of the app 

***video of bug***

https://youtu.be/UijQyFxTUkw

**Comment by alaskalinuxuser** [comment]
Thanks for the input! I've fixed this with commit https://github.com/alaskalinuxuser/app_JustChess/commit/3c7ed27ad0e00b3be6ecbb9bc62f00dfda243f40

Be sure to check out version 2.0 and thanks for the feedback!

**Comment by isreal6ix** [comment]
You welcome
