### ISSUE TITLE
The game restarts on screen rotation

### ISSUE THREAD

**Issue by neupanedipen** [alaskalinuxuser/app_JustChess#8]
#### Expected behavior<br>
The game must resume from the interface on which the screen was rotated on changing screen orientation.<br>
#### Actual behavior<br>
But the game restarts and the moves are cancelled in screen rotation.<br>
#### How to reproduce<br>
1. Install the app from Fdroid.<br>
2. Launch the app.<br>
3. Start the game and make some moves in the potrait mode.<br>
4. Now change the orientation of the screen to landscape mode.<br>
The moves are all removed and the game starts from the beginning.<br>
* App Version: 1.7<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/V3RdERapCyc<br>

**Comment by alaskalinuxuser** [comment]
Thanks for trying my app, and for reporting a bug! It helps me track things down. I no longer have an Android phone, so I was building this on an emulator and forgot about screen rotation. Fixed rotation destroying the game with this commit: https://github.com/alaskalinuxuser/app_JustChess/commit/a3241935e1ef42f5393eec944a7952106c002766

I still need to work on the look of the app when the screen is rotated.
